#cloud-config (redis)
#freeMusic.zone

# Upgrade the instance on first boot
package_upgrade: true

# create groups
groups:
  - redis-group

# create user
users:
  # the ec2-user
  - default
  # the system user for redis
  - name: redis_user
    gecos: Redis User
    system: true
    groups: redis-group

runcmd:
 # install redis
 - yum install redis -y --enablerepo=epel
 # configure redis
 - sed -i 's/bind 127.0.0.1/#bind 127.0.0.1/g' /etc/redis.conf
 - sed -i 's/# requirepass foobared/requirepass YOUR_SUPER_STRONG_PASSWORD/g' /etc/redis.conf
 # launch redis
 - su -l redis_user
 - service redis restart

final_message: "The redis server is finally up, after $UPTIME seconds"

output: {all: '| tee -a /var/log/cloud-init-output.log'}

# vim:syntax=yaml expandtab